//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipPlan
    {
        public System.Guid Id { get; set; }
        public Nullable<byte> NoOfMonths { get; set; }
        public Nullable<int> Fees { get; set; }
        public bool IsPlanExpired { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
