//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPVerification
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public int OTP { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
