//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReshimgathiDBContext : DbContext
    {
        public ReshimgathiDBContext()
            : base("name=ReshimgathiDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MembershipPlan> MembershipPlans { get; set; }
        public virtual DbSet<PaymentInformation> PaymentInformations { get; set; }
        public virtual DbSet<RequestContact> RequestContacts { get; set; }
        public virtual DbSet<UserProfileDetail> UserProfileDetails { get; set; }
        public virtual DbSet<UserProfilePicture> UserProfilePictures { get; set; }
        public virtual DbSet<OTPVerification> OTPVerifications { get; set; }
    
        [DbFunction("ReshimgathiDBContext", "GetLoginDetails")]
        public virtual IQueryable<GetLoginDetails_Result> GetLoginDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLoginDetails_Result>("[ReshimgathiDBContext].[GetLoginDetails]()");
        }
    
        public virtual int GetLoginDetailsProc(string input)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLoginDetailsProc", inputParameter);
        }
    }
}
