//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReshimgathiServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfilePicture
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserProfileId { get; set; }
        public string ImageURL { get; set; }
        public bool IsDefaultPicture { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual UserProfileDetail UserProfileDetail { get; set; }
    }
}
